executable="/usr/bin/arc"

[alias]
br="branch"
ps="push"
pl="pull"
prl="pr list"
prc="pr create --push --merge --publish -m"
cm="!arc-commit-ticket.sh \"$@\""
m="!arc-mount.sh"
ub="checkout -b"
gb="!arc-group-branches.sh"
rt="rebase trunk"
t="checkout trunk"
df="diff"
dfc="diff --cached"
cp="cherry-pick"
cp-svn="!arc-cherry-pick-svn-commit.sh \"$@\""