executable="/usr/bin/arc"

[alias]
br="branch"
ps="push"
pl="pull"
prl="pr list"
prc="pr create --push --merge -m"
cm="!arc-ticket-commit.sh \"$@\""
m="!arc-mount.sh"
ub="checkout -b"
gb="!arc-group-branches.sh"
rt="rebase --onto trunk"
t="checkout trunk"
df="diff"
dfc="diff --cached"