executable="/usr/bin/arc"

[alias]
br="branch"
ps="push"
pl="pull"
prl="pr list"
prc="!arc-create-pull-request.sh"
cm="!arc-ticket-comit.sh"
m="!arc-mount.sh"
ub="checkout -b"
gb="!arc-group-branches.sh"
rt="rebase --onto trunk"
