executable="/usr/bin/arc"

[alias]
br="branch"
cb="checkout -b"
cm="!arc-commit-ticket.sh \"$@\""
cp="cherry-pick"
cp-svn="!arc-cherry-pick-svn-commit.sh \"$@\""
df="diff"
dfc="diff --cached"
gb="!arc-group-branches.sh \"$@\""
m="!arc-mount.sh"
prc="pr create --push --merge --publish -m"
prl="pr list"
pl="pull"
ps="push"
rt="rebase trunk"
t="checkout trunk"
